# Generated by Django 5.2.15 on 2026-06-27 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnrollmentAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=128)),
                ("grade", models.PositiveSmallIntegerField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["region"], name="idx_aggregate_region"),
                    models.Index(fields=["grade"], name="idx_aggregate_grade"),
                    models.Index(
                        fields=["region", "grade"], name="idx_aggregate_region_grade"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "grade"), name="unique_region_grade_aggregate"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("region", models.CharField(db_index=True, max_length=128)),
                ("grade", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("processed", "PROCESSED"),
                            ("failed", "FAILED"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["region", "grade"], name="idx_enrollment_region_grade"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="idx_enrollment_status_created",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "processed")),
                        fields=("student_id",),
                        name="unique_processed_student",
                    )
                ],
            },
        ),
    ]
